name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /wwwroot/
          state-name: .ftp-deploy-sync-state.json # بيساعد في تتبع الملفات
          dangerous-clean-slate: false # تأكدي إنها false عشان ميمسحش ملفات السيرفر الأساسية